- type: job
  id: Secretarian
  name: job-name-secretarian
  description: job-description-secretarian
  playTimeTracker: JobSecretarian
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 20h # 20 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 20h # 20 hours
    - !type:OverallPlaytimeRequirement
      time: 60h #60 hrs
  weight: 20
  startingGear: SecretarianGear
  icon: "JobIconSecretarian"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  access:
  - Maintenance
  - External
  - Captain
  accessGroups:
  - Service
  - Command
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecretarianGear
  equipment:
    id: SecretarianPDA
    ears: ClothingHeadsetAltCommand
  inhand:
    - BriefcaseSecretaryFilled
